import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart



def send_email(email, height, average_height, count):
    port = 2525
    smtp_server = "smtp.mailtrap.io"
    login = "" # generated by Mailtrap
    password = "" # generated by Mailtrap

    sender_email = "mailtrap@example.com"
    receiver_email = email

    message = MIMEMultipart("alternative")
    message["Subject"] = "Height data"
    message["From"] = sender_email
    message["To"] = receiver_email

    # write the plain text part
    text = f"""\
    Hey there,
    your height is {height}.

    Average height of all is {average_height}
    and that is calculated out of {count} people.

    Thanks!
    """

    # write the HTML part
    html = f"""\
    <html>
      <body>
        <p>Hey there,</p>
        <p>your height is <strong>{height}</strong>.</p>
        <p>Average height of all is <strong>{average_height}</strong> and that is calculated out of <strong>{count}</strong> people</p>
        <p>Thanks!</p>
      </body>
    </html>
    """
    part1 = MIMEText(text, "plain")
    part2 = MIMEText(html, "html")
    message.attach(part1)
    message.attach(part2)

    with smtplib.SMTP("smtp.mailtrap.io", 2525) as server:
        server.login(login, password)
        server.sendmail(
            sender_email, receiver_email, message.as_string()
        )
    print('Sent')
